# ori_length.py
# Program to calculate the length of the Origin of Replication (Ori) in Vibrio cholerae

# DNA sequence of the Ori region (Vibrio cholerae)
ori = "ATCAATGATCAACGTAAGCTTCTAAGCATGATCAAGGTGCTCACACAGTTTATCCACAACCTGAGTGGATGACATCAAGATAGGTCGTTGTATCTCCTTCCTCTCGTACTCTCATGACCACGGAAAGATGATCAAGAGAGGATGATTTCTTGGCCATATCGCAATGAATACTTGTGACTTGTGCTTCCAATTGACATCTTCAGCGCCATATTGCGCTGGCCAAGGTGACGGAGCGGGATTACGAAAGCATGATCATGGCTGTTGTTCTGTTTATCTTGTTTTGACTGAGACTTGTTAGGATAGACGGTTTTTCATCACTGACTAGCCAAAGCCTTACTCTGCCTGACATCGACCGTAAATTGATAATGAATTTACATGCTTCCGCGACGATTTACCTCTTGATCATCGATCCGATTGAAGATCTTCAATTGTTAATTCTCTTGCCTCGACTCATAGCCATGATGAGCTCTTGATCATGTTTCCTTAACCCTCTATTTTTTACGGAAGAATGATCAAGCTGCTGCTCTTGATCATCGTTTC"  # full sequence

# Print the length of Ori
print("Length of Vibrio cholerae Ori sequence:", len(ori))

# Extra: Count nucleotides
nucleotide_counts = {
    "A": ori.count("A"),
    "T": ori.count("T"),
    "G": ori.count("G"),
    "C": ori.count("C")
}

print("Nucleotide counts:", nucleotide_counts)
