# Program to count the number of times a specific DNA pattern occurs
# in the Vibrio cholerae ori sequence.

def PatternCount(Text, Pattern):
    count = 0
    # Loop through each possible starting position
    for i in range(len(Text) - len(Pattern) + 1):
        # Check if the substring equals the pattern
        if Text[i:i+len(Pattern)] == Pattern:
            count += 1
    return count 

# Set Text equal to the oriC of Vibrio cholerae
Text = ("ATCAATGATCAACGTAAGCTTCTAAGCATGATCAAGGTGCTCACACAGTTTATCCACAACCTGAGTGGATGACATCAAGATAGGTCGTTGTATCTCCTTCCTCTCGTACTCTCATGACCACGGAAAGATGATCAAGAGAGGATGATTTCTTGGCCATATCGCAATGAATACTTGTGACTTGTGCTTCCAATTGACATCTTCAGCGCCATATTGCGCTGGCCAAGGTGACGGAGCGGGATTACGAAAGCATGATCATGGCTGTTGTTCTGTTTATCTTGTTTTGACTGAGACTTGTTAGGATAGACGGTTTTTCATCACTGACTAGCCAAAGCCTTACTCTGCCTGACATCGACCGTAAATTGATAATGAATTTACATGCTTCCGCGACGATTTACCTCTTGATCATCGATCCGATTGAAGATCTTCAATTGTTAATTCTCTTGCCTCGACTCATAGCCATGATGAGCTCTTGATCATGTTTCCTTAACCCTCTATTTTTTACGGAAGAATGATCAAGCTGCTGCTCTTGATCATCGTTTC")
Pattern = "TGATCA"

# Print the number of times Pattern occurs in Text
print(PatternCount(Text, Pattern))
